#####elasticsearch yaml ########
# ======================== Elasticsearch Configuration =========================
#
# NOTE: Elasticsearch comes with reasonable defaults for most settings.
#       Before you set out to tweak and tune the configuration, make sure you
#       understand what are you trying to accomplish and the consequences.
#
# The primary way of configuring a node is via this file. This template lists
# the most important settings you may want to configure for a production cluster.
#
# Please consult the documentation for further information on configuration options:
# https://www.elastic.co/guide/en/elasticsearch/reference/index.html
#
# ---------------------------------- Cluster -----------------------------------
#
# Use a descriptive name for your cluster:
#
cluster.name: vfe-logs-prod
#

# ------------------------------------ Node ------------------------------------
#
# Use a descriptive name for the node:
#
node.name: 'DCHQELASDATA11'
#
# Add custom attributes to the node:
node.data: true
#node.attr.data: hot
node.ingest: false
node.master: false
#node.attr.rack: r1
#
# ----------------------------------- Paths ------------------------------------
#
# Path to directory where to store the data (separate multiple locations by comma):
#
path.data: /elastic/disk1,/elastic/disk2,/elastic/disk3,/elastic/disk4
#
# Path to log files:
#
path.logs: /var/log/elasticsearch
#path.repo for backup
#path.repo: /backup
path.repo: ["/backup"]
# ----------------------------------- Memory -----------------------------------
#
# Lock the memory on startup:
#
#bootstrap.memory_lock: true
#
# Make sure that the heap size is set to about half the memory available
# on the system and that the owner of the process is allowed to use this
# limit.
#
# Elasticsearch performs poorly when the system is swapping the memory.
#
# ---------------------------------- Network -----------------------------------
#
# Set the bind address to a specific IP (IPv4 or IPv6):
#
network.host: 'DCHQELASDATA11'
#
# Set a custom port for HTTP:
#
#http.port: 9200
#
# For more information, consult the network module documentation.
# --------------------------------- Discovery ----------------------------------
discovery.seed_hosts: ["DCHQELASDATA01","DCHQELASDATA02","DCHQELASMASTER01","DCHQELASMASTER02","DCHQELASNGST01","DCHQELASNGST02","DCHQELASNGST03","DCHQELASDATA03","DCHQELASDATA04","DCHQELASMASTER03","DCHQELASDATA05","DCHQELASDATA06","DCHQELASDATA07","DCHQELASDATA08","DCHQELASDATA10"]

cluster.initial_master_nodes: ["DCHQELASMASTER01", "DCHQELASMASTER02" ,"DCHQELASMASTER03"]

# Pass an initial list of hosts to perform discovery when new node is started:
# The default list of hosts is ["127.0.0.1", "[::1]"]
#
#10.230.84.130   DCHQELASDATA01
#10.230.84.131   DCHQELASDATA02
#10.230.84.41    DCHQELASDATA03
#10.230.84.42    DCHQELASDATA04
#10.230.84.140   DCHQELASDATA05
#10.230.84.141   DCHQELASDATA06
#10.230.84.137   DCHQELASDATA07
#10.230.84.176   DCHQELASDATA08
#10.230.84.132   DCHQELASMASTER01
#10.230.84.133   DCHQELASMASTER02
#10.230.84.43    DCHQELASMASTER03
#10.230.84.134   DCHQELASNGST01
#10.230.84.135   DCHQELASDATA10
#10.230.84.82    DCHQELASNGST03

#discovery.zen.ping.unicast.hosts: ["DCHQELASDATA02","DCHQELASMASTER01","DCHQELASMASTER02","DCHQELASNGST01","DCHQELASNGST02","DCHQELASNGST03","DCHQELASDATA03","DCHQELASDATA04","DCHQELASMASTER03"]
#discovery.zen.ping.multicast.enable: false
# Prevent the "split brain" by configuring the majority of nodes (total number of master-eligible nodes / 2 + 1):
#
#discovery.zen.minimum_master_nodes: 2
#
# For more information, consult the zen discovery module documentation.
#
# ---------------------------------- Gateway -----------------------------------
#
# Block initial recovery after a full cluster restart until N nodes are started:
#
gateway.recover_after_nodes: 1
gateway.expected_nodes: 2
gateway.recover_after_time: 3m
# For more information, consult the gateway module documentation.
#
# ---------------------------------- Various -----------------------------------
#
# Require explicit names when deleting indices:
#
# action.destructive_requires_name: true
#
indices.query.bool.max_clause_count: 2000
###################################X-Pack Configs################################
xpack.security.transport.ssl.enabled: true
xpack.security.enabled: true
xpack.security.transport.ssl.verification_mode: certificate
xpack.security.transport.ssl.keystore.path: /etc/elasticsearch/certs/elastic-certificates.p12
xpack.security.transport.ssl.truststore.path: /etc/elasticsearch/certs/elastic-certificates.p12
indices.lifecycle.history_index_enabled: false

#xpack.notification.email.account:
#    exchange_account:
#        profile: outlook
#        email_defaults:
#            from: CRM.Notifications@vodafone.com
#        smtp:
 #           auth: false
#            starttls.enable: true
#            host: 10.230.95.91
#            port: 25
#xpack.security.enabled: false
